const EMPLOYEE={id:"KBR0003",password:"02192006",name:"James Arthur Buna"};const KEY="kape_barrio_dtr_"+EMPLOYEE.id,SESSION="kape_barrio_logged_in";const $=id=>document.getElementById(id);
function data(){try{return JSON.parse(localStorage.getItem(KEY))||{history:[],activeShift:null}}catch{return{history:[],activeShift:null}}}function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function dur(ms){let m=Math.max(0,Math.floor(ms/60000)),h=Math.floor(m/60),n=m%60;return h?(n?`${h} hour${h==1?"":"s"} ${n} minute${n==1?"":"s"}`:`${h} hour${h==1?"":"s"}`):`${n} minute${n==1?"":"s"}`}
function tm(s,sec=false){return new Date(s).toLocaleTimeString([],{hour:"numeric",minute:"2-digit",...(sec?{second:"2-digit"}:{})})}function dt(s){return new Date(s).toLocaleDateString([],{year:"numeric",month:"short",day:"numeric"})}
function login(){ $("loginScreen").classList.remove("hidden");$("dashboardScreen").classList.add("hidden");$("password").value="";$("loginError").textContent=""}function dash(){$("loginScreen").classList.add("hidden");$("dashboardScreen").classList.remove("hidden");render()}
function clock(){let n=new Date();$("currentDate").textContent=n.toLocaleDateString([],{weekday:"long",year:"numeric",month:"long",day:"numeric"});$("currentTime").textContent=tm(n,true);let d=data();if(d.activeShift)$("durationDisplay").textContent="Current shift: "+dur(Date.now()-new Date(d.activeShift.clockIn).getTime())}
function render(){let d=data(),a=d.activeShift,b=$("attendanceBtn");$("employeeName").textContent=EMPLOYEE.name;$("employeeId").textContent="Employee ID: "+EMPLOYEE.id;if(a){$("statusText").textContent="Currently working";$("clockInDisplay").textContent="Clocked in: "+tm(a.clockIn,true);$("clockInDisplay").classList.remove("hidden");$("durationDisplay").classList.remove("hidden");$("durationDisplay").textContent="Current shift: "+dur(Date.now()-new Date(a.clockIn).getTime());b.textContent="CLOCK OUT";b.classList.add("clock-out")}else{$("statusText").textContent="Ready to clock in";$("clockInDisplay").classList.add("hidden");$("durationDisplay").classList.add("hidden");b.textContent="CLOCK IN";b.classList.remove("clock-out")}history()}
function history(){let d=data(),body=$("historyBody");body.innerHTML="";if(!d.history.length){$("historyEmpty").classList.remove("hidden");$("historyTable").classList.add("hidden");return}$("historyEmpty").classList.add("hidden");$("historyTable").classList.remove("hidden");[...d.history].reverse().forEach(e=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${dt(e.clockIn)}</td><td>${tm(e.clockIn)}</td><td>${tm(e.clockOut)}</td><td><strong>${dur(e.durationMs)}</strong></td>`;body.appendChild(tr)})}
$("loginForm").onsubmit=e=>{e.preventDefault();if($("username").value.trim()===EMPLOYEE.id&&$("password").value===EMPLOYEE.password){sessionStorage.setItem(SESSION,"1");$("loginForm").reset();dash()}else $("loginError").textContent="Incorrect Employee ID or password."};
$("attendanceBtn").onclick=()=>{let d=data();if(!d.activeShift){d.activeShift={clockIn:new Date().toISOString()};save(d);$("actionMessage").textContent="Clock-in recorded."}else{let out=new Date().toISOString(),i=new Date(d.activeShift.clockIn).getTime(),o=new Date(out).getTime();d.history.push({clockIn:d.activeShift.clockIn,clockOut:out,durationMs:o-i});d.activeShift=null;save(d);$("actionMessage").textContent="Clock-out recorded. Shift completed."}render()};
$("logoutBtn").onclick=()=>{sessionStorage.removeItem(SESSION);login()};$("clearHistoryBtn").onclick=()=>{let d=data();if(d.history.length&&confirm("Clear all DTR history on this device? This cannot be undone.")){d.history=[];save(d);render()}};sessionStorage.getItem(SESSION)==="1"?dash():login();clock();setInterval(clock,1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});